---
title: "Advent Of Code 2020 | Day 1 - Day 3"
author: "Giuliano Sposito"
date: '2020-12-07'
slug: advent-of-code-2020-part_01
categories:
  - data science
tags:
  - en-US
  - rstats
  - tidyverse
  - data handling
keywords: tech
coverImage: /images/advent_of_code_header.jpg
thumbnailImage: /images/advent_of_code_tn.jpg
thumbnailImagePosition: left
metaAlignment: center

---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />


<p>Advent of Code is an Advent calendar of small programming puzzles for a variety of skill sets and skill levels that can be solved in any programming language you like. These are my six solutions to the ‘Advent of Code 2020’ puzzles, from day 1 to day 3, using R.</p>
<!--more-->
<p>Advent of Code is an Advent calendar of small programming puzzles for a variety of skill sets and skill levels that can be solved in any programming language you like. These are my six solutions to the ‘Advent of Code 2020’ puzzles, from day 1 to day 3, using R.</p>
<div id="advent-of-code" class="section level2">
<h2>Advent of Code</h2>
<p><a href="https://adventofcode.com/2020">Advent of Code</a> is an Advent calendar of small programming puzzles for a variety of skill sets and skill levels that can be solved in any programming language you like. You don’t need a computer science background to participate - just a little programming knowledge and some problem solving skills will get you pretty far. Nor do you need a fancy computer; every problem has a solution that completes in at most 15 seconds on ten-year-old hardware.</p>
<p>I try to answer the puzzles using R, let’s see what we get…</p>
</div>
<div id="day-1-report-repair" class="section level2">
<h2>Day 1: Report Repair</h2>
<div id="part-one" class="section level3">
<h3>Part One</h3>
<p>After saving Christmas five years in a row, you’ve decided to take a vacation at a nice resort on a tropical island. Surely, Christmas will go on without you.</p>
<p>The tropical island has its own currency and is entirely cash-only. The gold coins used there have a little picture of a starfish; the locals just call them stars. None of the currency exchanges seem to have heard of them, but somehow, you’ll need to find fifty of these coins by the time you arrive so you can pay the deposit on your room.</p>
<p>To save your vacation, you need to get all fifty stars by December 25th.</p>
<p>Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!</p>
<p>Before you leave, the Elves in accounting just need you to fix your expense report (your puzzle input); apparently, something isn’t quite adding up.</p>
<p>Specifically, they need you to find the two entries that sum to <code>2020</code> and then multiply those two numbers together.</p>
<p>For example, suppose your expense report contained the following:</p>
<pre><code>1721
979
366
299
675
1456</code></pre>
<p>In this list, the two entries that sum to <code>2020</code> are <code>1721</code> and <code>299.</code> Multiplying them together produces <code>1721 * 299 = 514579</code>, so the correct answer is 514579.</p>
<p>Of course, your expense report is much larger. Find the two entries that sum to 2020; what do you get if you multiply them together?</p>
<div id="solution" class="section level4">
<h4>Solution</h4>
<p>I’ll make a matrix with combination of 2 of all elements in the input, sum then up and check which pair has <code>2020</code> as result.</p>
<pre class="r"><code># solution using base r

# read the input as vector
input &lt;- read.csv(&quot;day01_input.txt&quot;, header = F)[,1]

# generate all combination of 2 
comb &lt;- combn(input, 2)

# sum each combinations
sums &lt;- colSums(comb)

# find which one has the sum equals 2020
vals &lt;- comb[,sums==2020]

# multiply them
resp &lt;- prod(vals)

resp</code></pre>
<pre><code>## [1] 866436</code></pre>
</div>
</div>
<div id="part-two" class="section level3">
<h3>Part two</h3>
<p>The Elves in accounting are thankful for your help; one of them even offers you a starfish coin they had left over from a past vacation. They offer you a second one if you can find three numbers in your expense report that meet the same criteria.</p>
<p>Using the above example again, the three entries that sum to <code>2020</code> are <code>979, 366,</code> and <code>675</code>. Multiplying them together produces the answer, <code>241861950</code>.</p>
<p>In your expense report, what is the product of the three entries that sum to 2020?</p>
<div id="solution-1" class="section level4">
<h4>Solution</h4>
<p>The same strategy, but in this case we make combinations of 3.</p>
<pre class="r"><code># keeping within base r

# generic solution for combinations of N
findCombSum &lt;- function(in.data, n.comb, match.value){

  # generate all combination of &#39;n.comb&#39; 
  comb &lt;- combn(in.data, n.comb)
  
  # sum each combinations
  sums &lt;- colSums(comb)
  
  # find which one has the sum equals &#39;match.value&#39;
  vals &lt;- comb[,sums==match.value]
  
  # multiply them
  resp &lt;- prod(vals)
  
  return(resp)
  
}

# read the input as vector
input &lt;- read.csv(&quot;day01_input.txt&quot;, header = F)[,1]

# part 1
findCombSum(input, 2, 2020)</code></pre>
<pre><code>## [1] 866436</code></pre>
<pre class="r"><code># part 2
findCombSum(input, 3, 2020)</code></pre>
<pre><code>## [1] 276650720</code></pre>
</div>
</div>
</div>
<div id="day-2-password-philosophy" class="section level2">
<h2>Day 2: Password Philosophy</h2>
<div id="parte-one" class="section level3">
<h3>Parte One</h3>
<p>Your flight departs in a few days from the coastal airport; the easiest way down to the coast from here is via toboggan.</p>
<p>The shopkeeper at the North Pole Toboggan Rental Shop is having a bad day. “Something’s wrong with our computers; we can’t log in!” You ask if you can take a look.</p>
<p>Their password database seems to be a little corrupted: some of the passwords wouldn’t have been allowed by the Official Toboggan Corporate Policy that was in effect when they were chosen.</p>
<p>To try to debug the problem, they have created a list (your puzzle input) of passwords (according to the corrupted database) and the corporate policy when that password was set.</p>
<p>For example, suppose you have the following list:</p>
<pre><code>1-3 a: abcde
1-3 b: cdefg
2-9 c: ccccccccc</code></pre>
<p>Each line gives the password policy and then the password. The password policy indicates the lowest and highest number of times a given letter must appear for the password to be valid. For example, <code>1-3 a</code> means that the password must contain <code>a</code> at <code>least 1</code> time and at <code>most 3</code> times.</p>
<p>In the above example, 2 passwords are valid. The middle password, <code>cdefg</code>, is not; it contains no instances of <code>b</code>, but needs <code>at least 1</code>. The first and third passwords are valid: they contain <code>one a or nine c</code>, both within the limits of their respective policies.</p>
<p>How many passwords are valid according to their policies?</p>
<div id="solution-2" class="section level4">
<h4>Solution</h4>
<p>I’ll process the input separating the policy and the password, after that we split the policy in the letter to be checked and the min and max appearing range.</p>
<pre class="r"><code># tidyr::separate() and stringr::str_count() come in handy for this
library(tidyverse)
library(kableExtra)
library(knitr)

# reads the input data as data frame with a column named &#39;input&#39;
password.check &lt;- read.csv(&quot;./day02_input.txt&quot;, header = F) %&gt;% 
  set_names(c(&quot;input&quot;)) %&gt;% 
  # splits each input into a password and a policy field
  separate(input, c(&quot;policy&quot;,&quot;password&quot;), sep=&quot;: &quot;, remove=F) %&gt;% 
  # splits the policy into range values and the letter to be checked
  separate(policy, c(&quot;pol.range.min&quot;, &quot;pol.range.max&quot;,&quot;pol.letter&quot;),
           sep=&quot;-| &quot;, convert=T) %&gt;% 
  # counts the number of letter to be checked appearing in the password and
  # checks if witin the policy range
  mutate( count.letter = str_count(password, pol.letter),  
          is.valid = count.letter &gt;= pol.range.min &amp;
                     count.letter &lt;= pol.range.max )

# let&#39;s see what we got
head(password.check) %&gt;% 
  kable() %&gt;% 
  kable_styling(font_size = 10)</code></pre>
<table class="table" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
input
</th>
<th style="text-align:right;">
pol.range.min
</th>
<th style="text-align:right;">
pol.range.max
</th>
<th style="text-align:left;">
pol.letter
</th>
<th style="text-align:left;">
password
</th>
<th style="text-align:right;">
count.letter
</th>
<th style="text-align:left;">
is.valid
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
16-18 h: hhhhhhhhhhhhhhhhhh
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:left;">
h
</td>
<td style="text-align:left;">
hhhhhhhhhhhhhhhhhh
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:left;">
TRUE
</td>
</tr>
<tr>
<td style="text-align:left;">
17-18 d: ddddddddddddddddzn
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:left;">
d
</td>
<td style="text-align:left;">
ddddddddddddddddzn
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:left;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:left;">
15-18 c: cccccccccccccczcczc
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:left;">
c
</td>
<td style="text-align:left;">
cccccccccccccczcczc
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:left;">
TRUE
</td>
</tr>
<tr>
<td style="text-align:left;">
3-9 r: pplzctdrc
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;">
r
</td>
<td style="text-align:left;">
pplzctdrc
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:left;">
4-14 d: lxdmddfddddddd
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:left;">
d
</td>
<td style="text-align:left;">
lxdmddfddddddd
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:left;">
TRUE
</td>
</tr>
<tr>
<td style="text-align:left;">
8-14 v: pvxlknfvplgktv
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:left;">
v
</td>
<td style="text-align:left;">
pvxlknfvplgktv
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
FALSE
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># how many password are valid?
sum(password.check$is.valid)</code></pre>
<pre><code>## [1] 465</code></pre>
</div>
</div>
<div id="part-two-1" class="section level3">
<h3>Part Two</h3>
<p>While it appears you validated the passwords correctly, they don’t seem to be what the Official Toboggan Corporate Authentication System is expecting.</p>
<p>The shopkeeper suddenly realizes that he just accidentally explained the password policy rules from his old job at the sled rental place down the street! The Official Toboggan Corporate Policy actually works a little differently.</p>
<p>Each policy actually describes two positions in the password, where 1 means the first character, 2 means the second character, and so on. (Be careful; Toboggan Corporate Policies have no concept of “index zero”!) Exactly one of these positions must contain the given letter. Other occurrences of the letter are irrelevant for the purposes of policy enforcement.</p>
<p>Given the same example list from above:</p>
<pre><code>1-3 a: abcde is valid: position 1 contains a and position 3 does not.
1-3 b: cdefg is invalid: neither position 1 nor position 3 contains b.
2-9 c: ccccccccc is invalid: both position 2 and position 9 contain c.</code></pre>
<p>How many passwords are valid according to the new interpretation of the policies?</p>
<div id="solution-3" class="section level4">
<h4>Solution</h4>
<p>I’ll use the same solution here, but change the interpretation of the policy following the new philosophy.</p>
<pre class="r"><code># tidyr::separate() and stringr::str_count() come in handy for this
library(tidyverse)

# reads the input data as data frame with a column named &#39;input&#39;
password.check &lt;- read.csv(&quot;./day02_input.txt&quot;, header = F) %&gt;% 
  set_names(c(&quot;input&quot;)) %&gt;% 
  # splits each input into the password and policy columns
  separate(input, c(&quot;policy&quot;,&quot;password&quot;), sep=&quot;: &quot;, remove=F) %&gt;% 
  # splits the policy into range/position values and the letter to be checke
  separate(policy, c(&quot;pol.range.min&quot;, &quot;pol.range.max&quot;,&quot;pol.letter&quot;),
           sep=&quot;-| &quot;, convert=T) %&gt;% 
  # part 1 
  # counts the number of letter to be checked appearing in the password and
  # checks if witin the policy range
  mutate( count.letter = str_count(password, pol.letter),  
          is.valid.part1 = count.letter &gt;= pol.range.min &amp;
                           count.letter &lt;= pol.range.max ) %&gt;% 
  # part 2
  # gets the letters in positions &#39;min&#39; and &#39;max&quot;&#39; and do a &quot;XOR&quot; check
  mutate(
    letter.at.pos1 = str_sub(password, pol.range.min, pol.range.min),
    letter.at.pos2 = str_sub(password, pol.range.max, pol.range.max),
    is.valid.part2 = xor(letter.at.pos1==pol.letter, letter.at.pos2==pol.letter)
  )

# part one: how many password are valid (repeat letter policy)?
sum(password.check$is.valid.part1)</code></pre>
<pre><code>## [1] 465</code></pre>
<pre class="r"><code># part tow: how many password are valid (letter at position xor policy?
sum(password.check$is.valid.part2)</code></pre>
<pre><code>## [1] 294</code></pre>
</div>
</div>
</div>
<div id="day-3-toboggan-trajectory" class="section level2">
<h2>Day 3: Toboggan Trajectory</h2>
<div id="part-1" class="section level3">
<h3>Part 1</h3>
<p>With the toboggan login problems resolved, you set off toward the airport. While travel by toboggan might be easy, it’s certainly not safe: there’s very minimal steering and the area is covered in trees. You’ll need to see which angles will take you near the fewest trees.</p>
<p>Due to the local geology, trees in this area only grow on exact integer coordinates in a grid. You make a map (your puzzle input) of the open squares (<code>.</code>) and trees (<code>#</code>) you can see. For example:</p>
<pre><code>..##.......
#...#...#..
.#....#..#.
..#.#...#.#
.#...##..#.
..#.##.....
.#.#.#....#
.#........#
#.##...#...
#...##....#
.#..#...#.#</code></pre>
<p>These aren’t the only trees, though; due to something you read about once involving arboreal genetics and biome stability, the same pattern repeats to the right many times:</p>
<pre><code>..##.........##.........##.........##.........##.........##.......  ---&gt;
#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..
.#....#..#..#....#..#..#....#..#..#....#..#..#....#..#..#....#..#.
..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#
.#...##..#..#...##..#..#...##..#..#...##..#..#...##..#..#...##..#.
..#.##.......#.##.......#.##.......#.##.......#.##.......#.##.....  ---&gt;
.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#
.#........#.#........#.#........#.#........#.#........#.#........#
#.##...#...#.##...#...#.##...#...#.##...#...#.##...#...#.##...#...
#...##....##...##....##...##....##...##....##...##....##...##....#
.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#  ---&gt;</code></pre>
<p>You start on the open square (<code>.</code>) in the top-left corner and need to reach the bottom (below the bottom-most row on your map).</p>
<p>The toboggan can only follow a few specific slopes (you opted for a cheaper model that prefers rational numbers); start by counting all the trees you would encounter for the slope right 3, down 1:</p>
<p>From your starting position at the top-left, check the position that is right 3 and down 1. Then, check the position that is right 3 and down 1 from there, and so on until you go past the bottom of the map.</p>
<p>The locations you’d check in the above example are marked here with <code>O</code> where there was an open square and <code>X</code> where there was a tree:</p>
<pre><code>..##.........##.........##.........##.........##.........##.......  ---&gt;
#..O#...#..#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..
.#....X..#..#....#..#..#....#..#..#....#..#..#....#..#..#....#..#.
..#.#...#O#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#
.#...##..#..X...##..#..#...##..#..#...##..#..#...##..#..#...##..#.
..#.##.......#.X#.......#.##.......#.##.......#.##.......#.##.....  ---&gt;
.#.#.#....#.#.#.#.O..#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#
.#........#.#........X.#........#.#........#.#........#.#........#
#.##...#...#.##...#...#.X#...#...#.##...#...#.##...#...#.##...#...
#...##....##...##....##...#X....##...##....##...##....##...##....#
.#..#...#.#.#..#...#.#.#..#...X.#.#..#...#.#.#..#...#.#.#..#...#.#  ---&gt;</code></pre>
<p>In this example, traversing the map using this slope would cause you to encounter 7 trees.</p>
<p>Starting at the top-left corner of your map and following a slope of right 3 and down 1, how many trees would you encounter?</p>
<div id="solution-4" class="section level4">
<h4>Solution</h4>
<p>The idea is to change the <code>tree char map</code> of dots and hashtags into a <code>0/1</code> matrix marking the trees with <code>1</code>. After that I iterate the trajectory to find the slope down positions (coordinates) until the end of the hill (bottom of the matrix). As the trees are repeating them pattern, it’s necessary to keep the <code>y-coordinate</code> in the range of the size of the matrix.</p>
<pre class="r"><code># reads the file as vector of string
input &lt;- read.csv(&quot;./day03_input.txt&quot;, header = F)[,1]

# creates a &quot;char&quot; matrix of &quot;.&quot; and &quot;#&quot;
char_map &lt;- strsplit(input, &quot;&quot;) %&gt;% 
  unlist() %&gt;% 
  matrix(nrow = length(input), byrow = T)

# converts in to 0 and 1 (1 for the trees) 
int_map &lt;- 1*(char_map == &quot;#&quot;)

# lets subset the matrix with the trajectory

# the hill trajectory: 3 to the left and 1 to the bottom
shift &lt;- c(1,3)

# starting from top left
base_pos &lt;- c(1,1)
trajectory &lt;- base_pos

# until the last row
for(i in 1:(nrow(int_map)-1)){
  step &lt;- base_pos + shift
  base_pos &lt;- step
  trajectory &lt;- rbind(trajectory, base_pos)
}

# keeps the y coord within the matrix range
y_coords &lt;- trajectory[,2] %% ncol(int_map)
y_coords[y_coords==0] &lt;- ncol(int_map) # adjust mod=0 is the most right y coord
trajectory[,2] &lt;- y_coords

# subsets the matrix in the trajectory and sum (count) the number of trees
sum(int_map[trajectory])</code></pre>
<pre><code>## [1] 237</code></pre>
</div>
</div>
<div id="part-2" class="section level3">
<h3>Part 2</h3>
<p>Time to check the rest of the slopes - you need to minimize the probability of a sudden arboreal stop, after all.</p>
<p>Determine the number of trees you would encounter if, for each of the following slopes, you start at the top-left corner and traverse the map all the way to the bottom:</p>
<pre><code>Right 1, down 1.
Right 3, down 1. (This is the slope you already checked.)
Right 5, down 1.
Right 7, down 1.
Right 1, down 2.</code></pre>
<p>In the above example, these slopes would find 2, 7, 3, 4, and 2 tree(s) respectively; multiplied together, these produce the answer 336.</p>
<p>What do you get if you multiply together the number of trees encountered on each of the listed slopes?</p>
<div id="solution-5" class="section level4">
<h4>Solution</h4>
<p>The same idea here, but I’ll make a generic solution (a function) to test several “slope strategy”.</p>
<pre class="r"><code># counts trees in a trajectory
# receives a int matrix where &quot;1&quot; is a tree and &quot;0&quot; not
# receives a &quot;shift pattern&quot; for each step down
countTreesByShift &lt;- function(shift.pattern, area.map){
  
  # starting from top left
  base_pos &lt;- c(1,1)
  trajectory &lt;- base_pos

  # apply the pattern until the bottom
  for(i in 1:(nrow(area.map)-1)){
    step &lt;- base_pos + shift.pattern
    base_pos &lt;- step
    trajectory &lt;- rbind(trajectory, step)
  }
  
  # keeps the y coord within the matrix range
  y_coords &lt;- trajectory[,2] %% ncol(area.map)
  y_coords[y_coords==0] &lt;- ncol(area.map)
  trajectory[,2] &lt;- y_coords
  
  # avoids out of index in the number of rows
  trajectory &lt;- trajectory[trajectory[,1]&lt;=nrow(area.map),]
  
  # subsets the map with trajectory coordinates and sum
  return(sum(int_map[trajectory]))
}

# reads the file as vector of string
input &lt;- read.csv(&quot;./day03_input.txt&quot;, header = F)[,1]

# creates a &quot;char&quot; matrix of &quot;.&quot; and &quot;#&quot;
char_map &lt;- strsplit(input, &quot;&quot;) %&gt;% 
  unlist() %&gt;% 
  matrix(nrow = length(input), byrow = T)

# converts in to 0 and 1 (1 for the trees) 
int_map &lt;- 1*(char_map == &quot;#&quot;)

# testing the patterns

# part 1
countTreesByShift(c(1,3),int_map)</code></pre>
<pre><code>## [1] 237</code></pre>
<pre class="r"><code># part 2
c(1,1,1,3,1,5,1,7,2,1) %&gt;% 
  matrix(ncol=2, byrow = T) %&gt;%
  split(1:nrow(.)) %&gt;% 
  purrr::map_dbl(countTreesByShift, area.map=int_map) %&gt;% 
  prod()</code></pre>
<pre><code>## [1] 2106818610</code></pre>
</div>
</div>
<div id="to-be-continued" class="section level3">
<h3>To be continued…</h3>
<p>I’ll make the rest of puzzles in the next days and publish them here, see you…</p>
</div>
</div>
